### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra/wix-shoov#2]
1. http://server2.web-stat.com/wixCurrencyPreview.pl
2. http://www.wix.com/demone2/boutique-recruitment-agency#!about/cjg9 - `exclude` only the people's image

**Comment by amitaibu** [comment]
Please add Shoov link of regression

**Comment by mldk-tech** [comment]
@amitaibu - https://app.shoov.io/#/screenshots/12508

**Comment by amitaibu** [comment]
Thanks.

**Comment by amitaibu** [comment]
Regression image:

![browserstack-chrome about 1 960px baseline](https://cloud.githubusercontent.com/assets/125707/10742608/b45cc454-7c36-11e5-8df5-a83e8b02b395.png)
