### ISSUE TITLE
Add visual monitor & Behat tests

### ISSUE THREAD

**Issue by amitaibu** [Gizra/wix-shoov#5]
http://www.wix.com/website-template/view/html/1701
http://www.wix.com/website-template/view/html/1710
http://www.wix.com/website-template/view/html/1692

**Comment by mldk-tech** [comment]
Link
http://www.wix.com/demone2/eyewear-store#!sale/c1ijr
Regression
https://app.shoov.io/#/screenshots/18888
Video
http://www.gfycat.com/ResponsiblePiercingBumblebee

**Comment by mldk-tech** [comment]
Link
http://www.wix.com/website-template/view/html/1710
Regression
https://app.shoov.io/#/screenshots/19178
Video
http://www.gfycat.com/SolidSerpentineGibbon

**Comment by mldk-tech** [comment]
Link
http://www.wix.com/demone2/indie-folk#!press/c15e9
Regression
https://app.shoov.io/#/screenshots/19178
Video
http://www.gfycat.com/SoreCheapCowbird

**Comment by mldk-tech** [comment]
Live monitoring video:
http://www.gfycat.com/NiceLastingAstarte

**Comment by amitaibu** [comment]
:+1:
